project 'Disparity Camera.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '11.0'


target 'Disparity Camera' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Disparity Camera

end
